"""
This module sets up and runs a Dash web app for visualizing mortgage payment schedules.

Utilizing data generated by the mortgage module, this app presents a stacked area chart
showing the breakdown of principal and interest payments over time, along with a detailed
table view of the payment schedule.

The app provides an interactive interface for users to explore how payments contribute
towards reducing the principal over the term of the mortgage.
"""

import dash
import plotly.graph_objs as go
from mortgage import generate_mortgage_schedule

# Create dataset of mortgage monthly payments
df_payments = generate_mortgage_schedule(
    principal=300000, annual_interest_rate=4.5 / 100, years=25
)

app = dash.Dash(__name__)

app.layout = dash.html.Div(
    children=[
        dash.html.H1(children="Mortgage Payments Overview"),
        dash.dcc.Graph(
            id="mortgage-stacked-area",
            figure={
                "data": [
                    go.Scatter(
                        x=df_payments["Month"],
                        y=df_payments["Principal Paid"],
                        stackgroup="one",
                        name="Principal Paid",
                    ),
                    go.Scatter(
                        x=df_payments["Month"],
                        y=df_payments["Interest Paid"],
                        stackgroup="one",
                        name="Interest Paid",
                    ),
                ],
                "layout": go.Layout(
                    title="Mortgage Payments (Principal vs Interest)",
                    xaxis={"title": "Month"},
                    yaxis={"title": "Amount Paid"},
                ),
            },
        ),
        dash.html.H2(children="Payment Details"),
        dash.dash_table.DataTable(
            id="table",
            columns=[{"name": i, "id": i} for i in df_payments.columns],
            data=df_payments.to_dict("records"),
        ),
    ]
)

if __name__ == "__main__":
    app.run_server(debug=True)
